/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val nombre: String = "Anti-Boggio" 
    var edad = 911 
    println("Hola $nombre") 
    println("Tengo ${edad + 1} años el próximo año") 
    println(App().greeting)
}
